CREATE TABLE IF NOT EXISTS groups 
    (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS songs
	(id INTEGER PRIMARY KEY, group_id INTEGER NOT NULL
	REFERENCES groups(id) ON DELETE CASCADE, song_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS song_info
		(song_id INTEGER PRIMARY KEY REFERENCES songs(id) ON DELETE CASCADE,
		lyrics TEXT NOT NULL, url TEXT NOT NULL);